### ISSUE TITLE
Event decoding support?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#109]
I'm not sure how is this aligned with this package purpose, but I see the overlapping parts:
- resolving of primitive type (like number => int)
- decoding events per different contracts defined in aci
- events looks like Fate values, so they should be consistently converted to JS
- support of additional types like Bits

The current implementation of events decoding in SDK lacks the mentioned above, I can fix it there, but I think would be better to propose event decoding implementation on calldata side.

related issue: https://github.com/aeternity/aepp-sdk-js/issues/1344

**Comment by marc0olo** [comment]
I think I was talking about sth. different in the related issue. but if we have problems with event decoding in general we should address it. I cannot really judge where it makes most sense.

**Comment by dincho** [comment]
> * support of additional types like Bits

This lib already support Bits ?

**Comment by dincho** [comment]
On the events subject, let me research a bit and I'll get back to you with my personal opinion

**Comment by dincho** [comment]
I started implementing this, however unfortunately the events log is not FATE encoded thus we can’t infer the data types, so type info should be provided by ACI. I don’t think this will solve the remote contract issue you’re referring to

**Comment by dincho** [comment]
Given an ACI, I would target full support of events decoding with the implementation

**Comment by davidyuk** [comment]
> I don’t think this will solve the remote contract issue you’re referring to

If ACI would include ACIs for remote contracts then we can decode the complete event list assigning each event to the corresponding contract. Currently, SDK decodes only events of the current/main contract, ignoring remote ones

> This lib already support Bits ?

Yep, and I would like to reuse this/do it in consistent way

**Comment by dincho** [comment]
> If ACI would include ACIs for remote contracts then we can decode the complete event list assigning each event to the corresponding contract.

Yes, that should work.

**Comment by marc0olo** [comment]
I added a comment after shortly discussing the remote events topic in combination with ACI together with Philipp here: https://github.com/aeternity/aepp-sdk-js/issues/1344#issuecomment-986027241

as I think this is related I just wanted to let you know about that here, too.
