### ISSUE TITLE
Not compatible with create-react-app

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#113]
- I've created a new project using `npx create-react-app my-project`
- added calldata there
- run `yarn build`:
```
$ yarn build
yarn run v1.22.10
$ react-scripts build
...
Creating an optimized production build...
Failed to compile.

./node_modules/@aeternity/aepp-calldata/src/Encoder.js
SyntaxError: /.../vue-reproductions/node_modules/@aeternity/aepp-calldata/src/Encoder.js: Support for the experimental syntax 'classPrivateProperties' isn't currently enabled (10:5):

   8 | class Encoder {
   9 |     /** @type {Object} */
> 10 |     #aci
     |     ^
  11 |
  12 |     /** @type {Serializer} */
  13 |     #serializer

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

reproduction: https://github.com/davidyuk/vue-reproductions/tree/react-calldata

The problem is that I can't find a way how to add a babel plugin without ejecting (or using `react-app-rewired` package). Seems reasonable to be compatible with `create-react-app` out of the box.

The similar ticket in `create-react-app` was closed with resolution: https://github.com/facebook/create-react-app/issues/9468#issuecomment-853246141
Also see: https://create-react-app.dev/docs/supported-browsers-features/#supported-language-features

Originally reported in https://github.com/emmanuelJet/aepp-boilerplate-react/issues/2

**Comment by marc0olo** [comment]
I see people complaining in the `create-react-app` repo about not supporting `??` operator. not sure where this should be solved.

let's see if the boilerplate works with the "workaround".
