### ISSUE TITLE
publish new release

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-calldata-js#115]
https://github.com/aeternity/aepp-sdk-js/pull/1365 depends on https://github.com/aeternity/aepp-calldata-js/pull/114 which is already merged. we should make a new release that we can refer to.

@dincho can you take care of this?

cc @davidyuk

**Comment by dincho** [comment]
[1.1.0](https://github.com/aeternity/aepp-calldata-js/releases/tag/v1.1.0) has been published including #114
