### ISSUE TITLE
Cannot resolve type: "MCL_BLS12_381.fp

### ISSUE THREAD

**Issue by genievot** [aeternity/aepp-calldata-js#126]
Linked https://github.com/aeternity/aeproject/issues/412

Thanks

**Comment by thepiwo** [comment]
> @thepiwo, Any progress on this ?

No updates from my side @dincho @marc0olo , do you have an update?

**Comment by marc0olo** [comment]
not yet - almost forgot about this in all the other trouble.

**Comment by marc0olo** [comment]
@genievot just talked to Dincho. we probably won't be able to provide this before end of april. maybe earlier if somebody else finds the time to look into it.

and even if we also need to update and release SDK. though you could at least run it locally with develop branch then.

**Comment by genievot** [comment]
Thanks for update @marc0olo . Can you provide other good tools where i can perform rapid tests of the smart contracts ? 
Any programming language will be fine.

**Comment by genievot** [comment]
thanks @marc0olo Currently I have a schedule so I will try to make it work somehow.

**Comment by dincho** [comment]
Isn't the http compiler works with this type ?

**Comment by marc0olo** [comment]
> Isn't the http compiler works with this type ?

good question. actually I don't know 😅 maybe @hanssv @ghallak @radrow can shortly answer?

**Comment by hanssv** [comment]
Sorry, what is the actual question? The compiler does know how to handle the `fp` (and the `fr`) type - but I guess that you're struggling with inputting values of these types? They should just be Montgomery-encoded numbers so inputting binaries of the right length should work, right? (Again, remember that contract call data are FATE-values not Sophia values!)

That said, I'm normally using integers as input when working with BLS12_381, i.e. I input a bunch of integers and build values using the `BLS12_381.mk_*`-functions and `BLS12_381.int_to_fr/fp`.

**Comment by genievot** [comment]
I think i am passing the wrong values in the test first here https://github.com/genievot/zk-ae-private-transactions/blob/main/test/zkp_verify_test.js#L36 . These bytes (I think) needs to be modulus of something big causing it to be become of size 32 bytes but it is 48 as you see despite being `fp` type. I think @hanssv is right that I should work with int...

**Comment by genievot** [comment]
thank you @dincho
