### ISSUE TITLE
`bad_call_data` when testing updated aex141-examples

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-calldata-js#160]
see https://github.com/aeternity/aex141-examples/pull/10

**Comment by marc0olo** [comment]
@davidyuk I shortly discussed that case with @dincho.

there is some investigation needed as we don't know what the exact problem is. I propose you dive into this analysis and come back to us with your results :)

reach out to me if you have questions

**Comment by marc0olo** [comment]
maybe @thepiwo can also analyze this if he finds some time 😅

**Comment by marc0olo** [comment]
I think we're on track now -> https://github.com/aeternity/aepp-calldata-js/pull/161/files

the pipeline failes :)

**Comment by dincho** [comment]
That’s not correct test case perhaps but yeah I somehow reproduced it
