### ISSUE TITLE
Decoding calldata without specifying method name

### ISSUE THREAD

**Issue by Kalovelo** [aeternity/aepp-calldata-js#170]
It would be of great use if we could somehow decode calldata without specifying the contract method that was used.

### State channel example
Let's say we have a channel open and there's a contract deployed there.
Whenever a participant calls a method, the other party is notified.

That party will need to decode the called data.
In order to do that, they will need to know which method was called.

Since `contract.calldata.decode()` needs a specific method name as an argument, a workaround would be to try/catch with each known contract method name until we correctly decode the data. However, as stated by @davidyuk:
_"Doing try/catch for each method is error-prone approach because this may wrongly detect method if they have the same return value type"_

On the other hand, `sdk.compilerApi.decodeCallResultBytecode` doesn't need a method name provided, as that is returned in its result (see below snippet). However, it is advised to keep compiler requests as minimal as possible, therefore a way to decode it in calldata-lib level would be really helpful

```js
const result = await channel.getContractCall({
      caller: responderConfig.responderId,
      contract: contractAddress,
      round: playerChannel.round(),
    });

// in case of contract call wasn't correct, this will throw a TypeError instead of 
// contract's error which would provide more explanation
const decodedContractValue = contract.calldata.decode(
      CONTRACT_NAME,
      // METHOD NAME MUST BE KNOWN
      contractMethods.methodName,
      result.returnValue,
    );

// more reliable
// this will display the contract result and in case of an error, 
// it will still be an object and provide context
const reliableData = await sdk.compilerApi.decodeCalldataBytecode({
    calldata,
    bytecode,
  });
// EXAMPLE STATE CHANNEL DEMO
const reliableData = await sdk.compilerApi.decodeCalldataBytecode({
    calldata,
    bytecode,
  });
console.log(reliableData);

// CASE CORRECT
/*
{
      function: 'reveal',
      result: {
				type: 'variant'
        value: [
          1,
          {
            type: 'address',
            value: 'ak_2H7zeWyMFiXCF1mAuDVNR1cTrx4vfqszQBh6fPEoeiFtjjhxtp',
          },
        ],
      },
    }
*/

// CASE ERROR
/*
{
  function: 'reveal',
  result: { abort: ['invalid_key_and_answer'] },
}
*/
```

**Comment by Kalovelo** [comment]
Turns out this is not required as decoding can be done through contract events

**Comment by davidyuk** [comment]
The ability to do the decoding without method name using sophia HTTP compiler makes reasonable to consider implementing the same in calldata library 🤔 

@Kalovelo let's keep issues that required to solve problem without the event-based workaround, opened

**Comment by dincho** [comment]
This is nice to have feature, and definitely possible. I hope I can find some time working on it soon. It also have other use cases not in the current ecosystem as well.

**Comment by dincho** [comment]
`BytecodeContractCallEncoder` has been added in #180
