### ISSUE TITLE
Catch undefined data to return proper error

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-calldata-js#175]
Currently, if e.g. one function call parameter is missed out, one is greeted with a rather generic error:

![image](https://user-images.githubusercontent.com/11761828/195331807-cd232fbb-35e4-4c19-9ffd-de80571b79e9.png)

Could we add a check to the constructors of the types returning a proper error if empty data is passed? Or, any other ideas for a less confusing error ?

**Comment by dincho** [comment]
Can we please start by providing an example code using only the library and then we move forward.

Screenshots of stacktraces is just lol

**Comment by nikita-fuchs** [comment]
I think this is handled on SDK level by now.
