### ISSUE TITLE
Convert to camelCase fields in result of ContractEncoder:decode

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#193]
https://github.com/aeternity/aepp-calldata-js/blob/dd31ff8e57eaaba5f567eedf9446b19f97c21b13/src/ContractEncoder.js#L21-L23

Naming variables in camel case is common approach in js  🤷‍♀️

**Comment by dincho** [comment]
done in https://github.com/aeternity/aepp-calldata-js/pull/190
