### ISSUE TITLE
Consider providing a build using es6 imports/exports

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#194]
Currently not very actual, but already some of the functionality is optional, so can be not used in specific cases, and would be good to be able to tree shake it. Tree shaking in webpack only works with es modules.

`.mjs` modules work natively in nodejs since 14 (the oldest maintainable version).

**Comment by dincho** [comment]
I did some experiments on this long time ago but there was some blockers I had hit.

I should re-try perhaps and document the blockers if it's still the case
