### ISSUE TITLE
support encoding/decoding of contracts (`ct_...`)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-calldata-js#69]
it should be possible to decode contract addresses like `ct_...` which is returned when returning e.g. a remote contract

**Example Contract**
```
contract interface OtherSophiaTypes =
    entrypoint testInt: (int) => int

main contract SophiaTypes =

    entrypoint testRemoteInt(remote : OtherSophiaTypes, intValue: int) :  int =
        remote.testInt(intValue)

    entrypoint testRemoteContract(remote : OtherSophiaTypes) : OtherSophiaTypes =
        remote
```

This trying to encode the calldata or decode the result leads to following error:
```js
Rejected promise returned by test. Reason:

  Error {
    message: 'Cannot resolve type: "OtherSophiaTypes"',
  }
```

**Comment by dincho** [comment]
This is already tested in https://github.com/aeternity/aepp-calldata-js/blob/master/tests/Decoder.js#L92-L103 I also tried to provoke it with explicitly setting the return type, but no difference.

Please provide library only minimal reproduction example, thanks

**Comment by marc0olo** [comment]
maybe the issue is/was addressing the wrong problem. seems like the calldata lib cannot handle the contract type.

I will check again and get back to you.

@dincho have you tested the example contract mentioned above?

**Comment by dincho** [comment]
I didn't tested a verbatim copy of the example as the test suite already have such a tests, with the little exception that the return type of the contract is implicit, but I also tried to change it to explicit, still works.

**Comment by dincho** [comment]
see https://github.com/aeternity/aepp-calldata-js/blob/master/contracts/Test.aes#L34 and https://github.com/aeternity/aepp-calldata-js/blob/master/contracts/Test.aes#L6-L7
