### ISSUE TITLE
Consistent variant encoding and decoding

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#74]
I have noticed that encoder accepts variants as `{ variant: 'Year', values: [] }`, but decodes as `{ Year: [] }`, would be better to use one approach in both cases, but I'm not sure which one is better.

**Comment by dincho** [comment]
> Can we use `FateVariant` externally?

No, I've provided an alternative data constructors in the related PR.

**Comment by dincho** [comment]
> to be more explicit in this case I personally would probably favor `{ variant: 'Year', values: [] }` as consistent representation

I was first lean to it as well, however the concise version somehow made a bit more sense in terms of public API, because you don't need to carry keys and keep them backward compatible.

Also I think the SDK is already utilizing that structure?

Please see the related PR
