### ISSUE TITLE
How to decode call result if the return type is not ok?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#88]
```JS
encoder.serializer.deserializeStream(decode(result.returnValue))[0].valueOf()
```
So far this looks like returning errors as strings properly, but would it work correctly in all cases? Do we need to define Fate types for `revert` and `error` return types?

Currently, SDK uses `decodeCallResult` compiler method for this.

cc: @dincho

**Comment by dincho** [comment]
No idea honestly, I should check how the reference implementation handles it

**Comment by dincho** [comment]
Looking the API https://api-docs.aeternity.io/#/external/GetTransactionInfoByHash there is return_value and return_type and rereading your question I don’t get it? You should get either error or revert return types in the mentioned cases IMO

**Comment by dincho** [comment]
The return_value always contain contract bytearray so this lib should be able to always decode it.

**Comment by davidyuk** [comment]
I have a problem with it. GetTransactionInfoByHash returned:
```
returnType: error
returnValue: cb_VHlwZSBlcnJvciBvbiBjYWxsOiBbe2J5dGVzLDw8MjQwLDIsLi4uPj59XSBpcyBub3Qgb2YgdHlwZSBbe2J5dGVzLDMyfV3EtJjU
```
using http compiler it decodes to:
```json
{
  "error": [
    "Type error on call: [{bytes,<<240,2,...>>}] is not of type [{bytes,32}]"
  ]
}
```
But the snippet at the top returns just 42n (😄) and 70 bytes of the rest stream:
```
FateInt { name: 'int', _value: 42n } Uint8Array(70) [
  121, 112, 101,  32, 101, 114, 114, 111, 114, 32, 111, 110,
   32,  99,  97, 108, 108,  58,  32,  91, 123, 98, 121, 116,
  101, 115,  44,  60,  60,  50,  52,  48,  44, 50,  44,  46,
   46,  46,  62,  62, 125,  93,  32, 105, 115, 32, 110, 111,
  116,  32, 111, 102,  32, 116, 121, 112, 101, 32,  91, 123,
   98, 121, 116, 101, 115,  44,  51,  50, 125, 93
]
```
applying it several times to the rest I got:
```
FateString { name: 'string', _value: 'pe error on call: [{bytes,<<24' } Uint8Array(39) [
   48,  44,  50,  44,  46,  46,  46,  62,  62,
  125,  93,  32, 105, 115,  32, 110, 111, 116,
   32, 111, 102,  32, 116, 121, 112, 101,  32,
   91, 123,  98, 121, 116, 101, 115,  44,  51,
   50, 125,  93
]
FateInt { name: 'int', _value: 24n } Uint8Array(38) [
   44,  50,  44,  46,  46,  46,  62,  62, 125,
   93,  32, 105, 115,  32, 110, 111, 116,  32,
  111, 102,  32, 116, 121, 112, 101,  32,  91,
  123,  98, 121, 116, 101, 115,  44,  51,  50,
  125,  93
]
FateInt { name: 'int', _value: 22n } Uint8Array(37) [
  50,  44,  46,  46,  46,  62,  62, 125,
  93,  32, 105, 115,  32, 110, 111, 116,
  32, 111, 102,  32, 116, 121, 112, 101,
  32,  91, 123,  98, 121, 116, 101, 115,
  44,  51,  50, 125,  93
]
FateInt { name: 'int', _value: 25n } Uint8Array(36) [
   44,  46,  46,  46,  62,  62, 125, 93,
   32, 105, 115,  32, 110, 111, 116, 32,
  111, 102,  32, 116, 121, 112, 101, 32,
   91, 123,  98, 121, 116, 101, 115, 44,
   51,  50, 125,  93
]
```

**Comment by davidyuk** [comment]
But it decodes just fine without calldata: `decode(result.returnValue).toString()`. Does it mean that I should use calldata only for `abort` results and plain conversion to string for `error`?

**Comment by dincho** [comment]
Thanks for the additional info, I'll try to grasp the error better now and get back to you

**Comment by dincho** [comment]
After a little bit of help from @hanssv it turns out that the error value is just plain string, but base64check encoded + prefix.

I've added basic help in #96 to easy the decoding, any suggestions are welcome.
