### ISSUE TITLE
Encoding is not working in projects based on @vue/cli@4 (webpack@4)

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#91]
I got an error

> Uncaught TypeError: "list" argument must be an Array of Buffers
    at Function.concat (index.js?b639:399)
    at Object.encode (base.js?6f08:10)
    at Encoder.encode (Encoder.js?db43:19)
    at eval (main.js?56d7:13)
    at Module../src/main.js (app.js:1159)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.1 (app.js:1172)
    at __webpack_require__ (app.js:849)
    at checkDeferredModules (app.js:46)

while doing `(new Encoder(aci)).encode('Test', 'init', [])`.
The reproduction is here: https://github.com/davidyuk/vue-reproductions/blob/calldata-buffer/src/main.js

I've made some investigation around this. Webpack 4 emulates node stuff in browser using `node-libs-browser@2.21`. That package provides `buffer@4.3.0`.

`concat` method of `buffer@6.0.3` supports Uint8Arrays: https://github.com/feross/buffer/blob/088fd9709e95f96b1f64d1c55ed3c50a19c73e9f/index.js#L411-L421

`concat` method of `buffer@4.9.2` doesn't: https://github.com/feross/buffer/blob/da2e3fcbf0416b79ec0c56c348bc7efd98d9ff37/index.js#L396-L403

`encode` method of calldata invokes `base64check.encode` with Uint8Array in arguments: https://github.com/aeternity/aepp-calldata-js/blob/031e0a80af1cc9d4505040eba30d7f899108f7f4/src/Encoder.js#L19

`base64check` does `Buffer.concat` with payload and checksum: https://github.com/magnumwallet/base64check/blob/375836692ae6677e5b7381b545a70944140476d2/base.js#L10-L13

`base64check` depends on `safe-buffer` that does not explicitly define buffer it depends on: https://github.com/feross/safe-buffer/blob/bc5ead0f17e0da69bb97f727d19787778b738acc/index.js#L3

So, because of all this, `calldata` is not working in @vue/cli (and probably Webpack 4) in the default configuration, but it works fine in Webpack 5.

**Comment by marc0olo** [comment]
@dincho what's your take on this one?

**Comment by dincho** [comment]
@marc0olo I still have to take a look, next item in my queue for this project

**Comment by dincho** [comment]
@davidyuk any proposition? On first look I'd say adding newer buffer version as calldata dep

**Comment by davidyuk** [comment]
> adding newer buffer version as calldata dep

Then it doesn't gets pick up by `base64check`, from the reproduction above:
```
node_modules/@aeternity
└── aepp-calldata
    ├── node_modules
    │   └── buffer
    └── src
node_modules/base64check
```

It works after changing Encoder in calldata:
```diff
@@ -1,5 +1,6 @@
 const blake = require('blakejs')
 const base64check = require('base64check')
+const { Buffer } = require('buffer')
 const Serializer = require('./Serializer')
 const FateByteArray = require('./types/FateByteArray')
 const FateTuple = require('./types/FateTuple')
@@ -17,7 +18,7 @@ class Encoder {
     }
 
     encode(contract, funName, args) {
-        return 'cb_' + base64check.encode(this.serialize(contract, funName, args))
+        return 'cb_' + base64check.encode(Buffer.from(this.serialize(contract, funName, args)))
     }
 
     decode(contract, funName, data) {
```

but then we don't need explicit dependency on the latest Buffer in package.json (as `base64check ` does), `buffer@4` should work fine here too.

As alternative consider replacing of `base64check` package, seems we the only one user of it and it was maintained by abandoned crypto wallet. In SDK we implemented it by ourselves: https://github.com/aeternity/aepp-sdk-js/blob/d3b381ba8b19d3c0cc55bf5179383d39e851ca4a/src/utils/crypto.js#L95-L133

**Comment by dincho** [comment]
Yeah, looks like dropping the dep and copying the code (several lines only) is not that bad idea in npm world
