### ISSUE TITLE
Generate TypeScript types for code generation

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-calldata-js#97]
Later we are planning to generate typescript definitions corresponding to contract interfaces. The ability to generate TypeScript type as a string corresponding to method arguments is needed there. The call arguments would be passed to the calldata, so looks reasonable to define it here to keep consistent with implementation.

related issue: https://github.com/aeternity/aepp-sdk-js/issues/1234

**Comment by dincho** [comment]
I’m not familiar with TS generator, I’ve to read a bit on it. As long that’s not required during development but it’s only a build artifact I don’t mind. However the lib code must stay in plain JS, that is it shouldn’t be mandatory to use a TS traspiler to use it

**Comment by dincho** [comment]
OK, it turns out the idea is to generate TS interfaces from ACI with the help of this lib IR data structures.

**Comment by dincho** [comment]
New year, fresh mind - I don't think this functionality belongs to calldata library. Any tool can parse the ACI and generate the corresponding TS interfaces given the calldata data types are well documented i.e. string maps to string bool to bool etc.

**Comment by davidyuk** [comment]
This is correct, but type generation should be in sync with calldata functionality, would be easier to do so by keeping type generation in the same repository.

I've checked recently how to generate code in typescript, it is pretty straightforward, the only `typescript` package needed 
https://github.com/aeternity/aepp-sdk-js/blob/develop/tooling/generate-schema.ts
